//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.06 at 04:13:45 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://learn-everyday.com/courses", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.learn_everyday.courses;
